version: '3.9'

services:

  sqlserver:
    image: tthanhphuc/database_repository:latest
    container_name: sqlserverr
    restart: unless-stopped
    environment:
      - SA_PASSWORD=2104110080A@
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U sa -P "2104110080A@" -Q 'SELECT 1'
      interval: 5s
      timeout: 2s
      retries: 5
  sqlserver.configurator:
    image: tthanhphuc/database_repository:latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 2104110080A@ -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '

  frontend:
    image: aogiench/bookstore:frontend  
    restart: unless-stopped
    ports:
      - 3000:3000  
    environment:
      - SPRING_API_URL=http://spring-rest:8080  
    depends_on:
      - spring-rest

  spring-rest:
    image: tthanhphuc/bookstore:latest
    container_name: spring-bookstoree
    restart: unless-stopped
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=bookstore;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=2104110080A@

volumes:
  sqlserver-data: